version: "3.9"
services:
  spotdl:
    build:
      context: .
      args:
        UID: "${PUID:-1000}"
        GID: "${PGID:-1000}"
    image: "spotdl/spotify-downloader"
    volumes:
      - spotdl_music:/music
    environment:
      - TZ=${TZ:-UTC}

volumes:
  spotdl_music:
