"""initial schema — the full spec §6.1 schema (THE anti-churn contract).

Creates every table/column/constraint/index defined in ``db/models.py``,
including the Plan-7-reserved pieces (the ``download_batches`` table, the
``BatchKind`` enum column, and ``download_jobs.batch_id`` / ``list_position`` /
``skip_reason`` / ``attempts``) so Plans 6 and 7 add only NEW tables and ship
zero migrations against this schema. Enums render as non-native VARCHAR + CHECK
on both dialects; the naming convention makes DDL deterministic across SQLite
and Postgres. ``downgrade()`` drops tables in FK-safe order (``download_jobs``
before ``download_batches``). The ``test_migrations`` autogenerate-parity test
mechanically enforces that this migration mirrors ``Base.metadata`` exactly.

Revision ID: 0001
Revises:
Create Date: 2026-07-09

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('album_artist', sa.String(length=1024), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('track_count', sa.Integer(), nullable=True),
    sa.Column('cover_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_albums'))
    )
    op.create_table('artists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('normalized_name', sa.String(length=1024), nullable=False),
    sa.Column('genres', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artists')),
    sa.UniqueConstraint('normalized_name', name='uq_artists_normalized_name')
    )
    op.create_table('download_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('SINGLE', 'ALBUM', 'PLAYLIST', name='batchkind', native_enum=False, length=32), nullable=False),
    sa.Column('source', sa.String(length=2048), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('output_format', sa.String(length=16), nullable=True),
    sa.Column('bitrate', sa.String(length=16), nullable=True),
    sa.Column('output_template', sa.String(length=2048), nullable=True),
    sa.Column('overwrite', sa.String(length=16), nullable=True),
    sa.Column('generate_m3u', sa.Boolean(), nullable=False),
    sa.Column('m3u_template', sa.String(length=2048), nullable=True),
    sa.Column('generate_save_file', sa.Boolean(), nullable=False),
    sa.Column('save_file_path', sa.String(length=2048), nullable=True),
    sa.Column('update_archive', sa.Boolean(), nullable=False),
    sa.Column('embed_lyrics', sa.Boolean(), nullable=False),
    sa.Column('generate_lrc', sa.Boolean(), nullable=False),
    sa.Column('sponsor_block', sa.Boolean(), nullable=False),
    sa.Column('total_jobs', sa.Integer(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_download_batches'))
    )
    with op.batch_alter_table('download_batches', schema=None) as batch_op:
        batch_op.create_index('ix_download_batches_requested_by', ['requested_by'], unique=False)

    op.create_table('playlists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=512), nullable=True),
    sa.Column('cover_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playlists'))
    )
    op.create_table('provider_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('SPOTIFY', 'DEEZER', 'ITUNES', 'MUSICBRAINZ', 'YTMUSIC', 'YOUTUBE', 'SOUNDCLOUD', 'BANDCAMP', 'PIPED', 'LRCLIB', 'GENIUS', 'MUSIXMATCH', 'AZLYRICS', name='providerid', native_enum=False, length=32), nullable=False),
    sa.Column('provider_entity_id', sa.String(length=256), nullable=False),
    sa.Column('entity_type', sa.Enum('TRACK', 'ALBUM', 'ARTIST', 'PLAYLIST', name='entitytype', native_enum=False, length=32), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('isrc', sa.String(length=32), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('artist_names', sa.JSON(), nullable=True),
    sa.Column('album_name', sa.String(length=1024), nullable=True),
    sa.Column('art_url', sa.String(length=2048), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_snapshots')),
    sa.UniqueConstraint('provider', 'provider_entity_id', name='uq_provider_snapshots_provider_entity')
    )
    with op.batch_alter_table('provider_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_provider_snapshots_isrc', ['isrc'], unique=False)
        batch_op.create_index('ix_provider_snapshots_provider_entity_type', ['provider', 'entity_type'], unique=False)

    op.create_table('entity_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('TRACK', 'ALBUM', 'ARTIST', 'PLAYLIST', name='entitytype', native_enum=False, length=32), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('AUTO', 'VERIFIED', 'DISPUTED', name='linkstatus', native_enum=False, length=32), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('downvotes', sa.Integer(), nullable=False),
    sa.Column('net_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['provider_snapshots.id'], name=op.f('fk_entity_links_snapshot_id_provider_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_links')),
    sa.UniqueConstraint('entity_type', 'entity_id', 'snapshot_id', name='uq_entity_links_entity_type_entity_id_snapshot_id')
    )
    with op.batch_alter_table('entity_links', schema=None) as batch_op:
        batch_op.create_index('ix_entity_links_entity_type_entity_id', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_entity_links_snapshot_id', ['snapshot_id'], unique=False)

    op.create_table('tracks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('isrc', sa.String(length=32), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=True),
    sa.Column('track_number', sa.Integer(), nullable=True),
    sa.Column('disc_number', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('album_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('fk_tracks_album_id_albums'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracks'))
    )
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.create_index('ix_tracks_album_id', ['album_id'], unique=False)
        batch_op.create_index('ix_tracks_isrc', ['isrc'], unique=False)

    op.create_table('lyrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('SPOTIFY', 'DEEZER', 'ITUNES', 'MUSICBRAINZ', 'YTMUSIC', 'YOUTUBE', 'SOUNDCLOUD', 'BANDCAMP', 'PIPED', 'LRCLIB', 'GENIUS', 'MUSIXMATCH', 'AZLYRICS', name='providerid', native_enum=False, length=32), nullable=False),
    sa.Column('kind', sa.Enum('PLAIN', 'SYNCED', name='lyricskind', native_enum=False, length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('downvotes', sa.Integer(), nullable=False),
    sa.Column('net_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_lyrics_track_id_tracks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lyrics')),
    sa.UniqueConstraint('track_id', 'source', 'kind', name='uq_lyrics_track_id_source_kind')
    )
    with op.batch_alter_table('lyrics', schema=None) as batch_op:
        batch_op.create_index('ix_lyrics_track_id', ['track_id'], unique=False)

    op.create_table('matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('target_provider', sa.Enum('SPOTIFY', 'DEEZER', 'ITUNES', 'MUSICBRAINZ', 'YTMUSIC', 'YOUTUBE', 'SOUNDCLOUD', 'BANDCAMP', 'PIPED', 'LRCLIB', 'GENIUS', 'MUSIXMATCH', 'AZLYRICS', name='providerid', native_enum=False, length=32), nullable=False),
    sa.Column('target_id', sa.String(length=512), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('matcher_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('AUTO', 'COMMUNITY_VERIFIED', 'REJECTED', name='matchstatus', native_enum=False, length=32), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('candidate_name', sa.String(length=1024), nullable=True),
    sa.Column('candidate_artists', sa.JSON(), nullable=True),
    sa.Column('candidate_duration_ms', sa.Integer(), nullable=True),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('downvotes', sa.Integer(), nullable=False),
    sa.Column('net_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_matches_track_id_tracks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches')),
    sa.UniqueConstraint('track_id', 'target_provider', 'target_id', name='uq_matches_track_id_target_provider_target_id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_track_id'), ['track_id'], unique=False)
        batch_op.create_index('ix_matches_track_id_status', ['track_id', 'status'], unique=False)

    op.create_table('playlist_tracks',
    sa.Column('playlist_id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name=op.f('fk_playlist_tracks_playlist_id_playlists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_playlist_tracks_track_id_tracks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id', 'track_id', name=op.f('pk_playlist_tracks'))
    )
    with op.batch_alter_table('playlist_tracks', schema=None) as batch_op:
        batch_op.create_index('ix_playlist_tracks_track_id', ['track_id'], unique=False)

    op.create_table('track_artists',
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('artist_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_track_artists_artist_id_artists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_track_artists_track_id_tracks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', 'artist_id', name=op.f('pk_track_artists'))
    )
    with op.batch_alter_table('track_artists', schema=None) as batch_op:
        batch_op.create_index('ix_track_artists_artist_id', ['artist_id'], unique=False)

    op.create_table('download_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('track_id', sa.Uuid(), nullable=True),
    sa.Column('match_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='downloadstatus', native_enum=False, length=32), nullable=False),
    sa.Column('list_position', sa.Integer(), nullable=True),
    sa.Column('output_format', sa.String(length=16), nullable=True),
    sa.Column('bitrate', sa.String(length=16), nullable=True),
    sa.Column('output_template', sa.String(length=2048), nullable=True),
    sa.Column('output_path', sa.String(length=2048), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_step', sa.String(length=32), nullable=True),
    sa.Column('skip_reason', sa.String(length=32), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['download_batches.id'], name=op.f('fk_download_jobs_batch_id_download_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_download_jobs_match_id_matches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_download_jobs_track_id_tracks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_download_jobs'))
    )
    with op.batch_alter_table('download_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_jobs_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index('ix_download_jobs_status', ['status'], unique=False)
        batch_op.create_index('ix_download_jobs_track_id', ['track_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_download_jobs_track_id')
        batch_op.drop_index('ix_download_jobs_status')
        batch_op.drop_index(batch_op.f('ix_download_jobs_batch_id'))

    op.drop_table('download_jobs')
    with op.batch_alter_table('track_artists', schema=None) as batch_op:
        batch_op.drop_index('ix_track_artists_artist_id')

    op.drop_table('track_artists')
    with op.batch_alter_table('playlist_tracks', schema=None) as batch_op:
        batch_op.drop_index('ix_playlist_tracks_track_id')

    op.drop_table('playlist_tracks')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index('ix_matches_track_id_status')
        batch_op.drop_index(batch_op.f('ix_matches_track_id'))

    op.drop_table('matches')
    with op.batch_alter_table('lyrics', schema=None) as batch_op:
        batch_op.drop_index('ix_lyrics_track_id')

    op.drop_table('lyrics')
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index('ix_tracks_isrc')
        batch_op.drop_index('ix_tracks_album_id')

    op.drop_table('tracks')
    with op.batch_alter_table('entity_links', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_links_snapshot_id')
        batch_op.drop_index('ix_entity_links_entity_type_entity_id')

    op.drop_table('entity_links')
    with op.batch_alter_table('provider_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_provider_snapshots_provider_entity_type')
        batch_op.drop_index('ix_provider_snapshots_isrc')

    op.drop_table('provider_snapshots')
    op.drop_table('playlists')
    with op.batch_alter_table('download_batches', schema=None) as batch_op:
        batch_op.drop_index('ix_download_batches_requested_by')

    op.drop_table('download_batches')
    op.drop_table('artists')
    op.drop_table('albums')
    # ### end Alembic commands ###
