"""community layer — the six §6.1 deferred tables (Plan 6).

Additive-only: creates ``users``, ``api_tokens``, ``oauth_identities``,
``refresh_tokens``, ``reports`` and ``votes`` and touches NO Plan-5 table (every
``batch_alter_table`` below creates an index on a freshly-created table). Enums
render as non-native VARCHAR + CHECK on both dialects; ``votes.value`` carries a
``CHECK value IN (-1, 1)``; ``votes.votable_id`` / ``reports.subject_id`` are
polymorphic ids with no cross-table FK. ``downgrade()`` drops the six tables in
FK-safe order (children before ``users``). The ``test_migrations`` autogenerate-
parity test mechanically enforces this migration mirrors ``Base.metadata``.

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-09

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token_prefix', sa.String(length=24), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_tokens')),
    sa.UniqueConstraint('token_hash', name='uq_api_tokens_token_hash')
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_api_tokens_token_prefix', ['token_prefix'], unique=False)
        batch_op.create_index('ix_api_tokens_user_id', ['user_id'], unique=False)

    op.create_table('oauth_identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('GITHUB', 'DISCORD', name='oauthprovider', native_enum=False, length=32), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('provider_username', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_identities')),
    sa.UniqueConstraint('provider', 'provider_account_id', name='uq_oauth_identities_provider_provider_account_id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_oauth_identities_user_id_provider')
    )
    with op.batch_alter_table('oauth_identities', schema=None) as batch_op:
        batch_op.create_index('ix_oauth_identities_user_id', ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name='uq_refresh_tokens_token_hash')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_refresh_tokens_family_id', ['family_id'], unique=False)
        batch_op.create_index('ix_refresh_tokens_user_id', ['user_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reporter_id', sa.Uuid(), nullable=True),
    sa.Column('subject_type', sa.Enum('TRACK', 'ALBUM', 'ARTIST', 'PLAYLIST', name='entitytype', native_enum=False, length=32), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=True),
    sa.Column('proposed_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='reportstatus', native_enum=False, length=32), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_reports_reporter_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_reports_reviewed_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('ix_reports_reporter_id', ['reporter_id'], unique=False)
        batch_op.create_index('ix_reports_status', ['status'], unique=False)
        batch_op.create_index('ix_reports_subject_type_subject_id', ['subject_type', 'subject_id'], unique=False)

    op.create_table('votes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('votable_type', sa.Enum('MATCH', 'LYRICS', 'ENTITY_LINK', name='votabletype', native_enum=False, length=32), nullable=False),
    sa.Column('votable_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('value IN (-1, 1)', name=op.f('ck_votes_value_in_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_votes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_votes')),
    sa.UniqueConstraint('user_id', 'votable_type', 'votable_id', name='uq_votes_user_id_votable_type_votable_id')
    )
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_index('ix_votes_votable_type_votable_id', ['votable_type', 'votable_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_index('ix_votes_votable_type_votable_id')

    op.drop_table('votes')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index('ix_reports_subject_type_subject_id')
        batch_op.drop_index('ix_reports_status')
        batch_op.drop_index('ix_reports_reporter_id')

    op.drop_table('reports')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_refresh_tokens_user_id')
        batch_op.drop_index('ix_refresh_tokens_family_id')

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('oauth_identities', schema=None) as batch_op:
        batch_op.drop_index('ix_oauth_identities_user_id')

    op.drop_table('oauth_identities')
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_api_tokens_user_id')
        batch_op.drop_index('ix_api_tokens_token_prefix')

    op.drop_table('api_tokens')
    op.drop_table('users')
    # ### end Alembic commands ###
