"""ui metadata stats fields — multi-provider metadata + time-series stats.

Additive-only (Phase 1b of the v5 UI/metadata/stats redesign):

* Widens ``albums`` (label / copyright_text / popularity / genres / album_type),
  ``artists`` (popularity / followers / bio / country / header_url) and ``tracks``
  (date / publisher / copyright_text) with the Spotify-first merged metadata the
  new UI renders. Every added column is nullable except ``albums.genres``, which
  mirrors the existing ``artists.genres`` / ``tracks.genres`` shape (NOT NULL,
  Python-side ``default=list``) and carries a ``'[]'`` server default so the ALTER
  is safe on an already-populated table.
* Adds the ``entity_stat`` time-series table (one row per entity/provider/metric
  capture) that powers the Stats panel. Collection is deferred to a later phase —
  this migration is schema only. Column adds use ``batch_alter_table`` so the
  ALTERs render as SQLite-safe table rebuilds and stay Postgres-compatible.

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-10 03:26:56.433801

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_stat',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('TRACK', 'ALBUM', 'ARTIST', 'PLAYLIST', name='entitytype', native_enum=False, length=32), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('SPOTIFY', 'DEEZER', 'ITUNES', 'MUSICBRAINZ', 'YTMUSIC', 'YOUTUBE', 'SOUNDCLOUD', 'BANDCAMP', 'PIPED', 'LRCLIB', 'GENIUS', 'MUSIXMATCH', 'AZLYRICS', name='providerid', native_enum=False, length=32), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_stat'))
    )
    with op.batch_alter_table('entity_stat', schema=None) as batch_op:
        batch_op.create_index('ix_entity_stat_entity_type_entity_id_metric', ['entity_type', 'entity_id', 'metric'], unique=False)

    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('copyright_text', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('popularity', sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column('genres', sa.JSON(), nullable=False, server_default=sa.text("'[]'"))
        )
        batch_op.add_column(sa.Column('album_type', sa.String(length=32), nullable=True))

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('popularity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('followers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('header_url', sa.String(length=2048), nullable=True))

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('publisher', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('copyright_text', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_column('copyright_text')
        batch_op.drop_column('publisher')
        batch_op.drop_column('date')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_column('header_url')
        batch_op.drop_column('country')
        batch_op.drop_column('bio')
        batch_op.drop_column('followers')
        batch_op.drop_column('popularity')

    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_column('album_type')
        batch_op.drop_column('genres')
        batch_op.drop_column('popularity')
        batch_op.drop_column('copyright_text')
        batch_op.drop_column('label')

    with op.batch_alter_table('entity_stat', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_stat_entity_type_entity_id_metric')

    op.drop_table('entity_stat')
    # ### end Alembic commands ###
