"""artist discography — artist→albums association + album source ref.

Additive-only (artist discography feature):

* Adds the ``artist_albums`` ordered many-to-many association (artist_id,
  album_id, position) linking an artist to the albums of its discography —
  mirrors ``track_artists``. ``Artist.albums`` hangs off it.
* Widens ``albums`` with ``provider`` / ``provider_id`` (the highest-priority
  source ref) so a metadata-only discography album can be resolve-refreshed via
  ``{provider}:album:{provider_id}``. Both nullable — existing rows stay valid.

Column adds use ``batch_alter_table`` so the ALTERs render as SQLite-safe table
rebuilds and stay Postgres-compatible.

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-10

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_albums',
    sa.Column('artist_id', sa.Uuid(), nullable=False),
    sa.Column('album_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('fk_artist_albums_album_id_albums'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_artist_albums_artist_id_artists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artist_id', 'album_id', name=op.f('pk_artist_albums'))
    )
    with op.batch_alter_table('artist_albums', schema=None) as batch_op:
        batch_op.create_index('ix_artist_albums_album_id', ['album_id'], unique=False)

    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'provider',
                sa.Enum(
                    'SPOTIFY', 'DEEZER', 'ITUNES', 'MUSICBRAINZ', 'YTMUSIC', 'YOUTUBE',
                    'SOUNDCLOUD', 'BANDCAMP', 'PIPED', 'LRCLIB', 'GENIUS', 'MUSIXMATCH',
                    'AZLYRICS', name='providerid', native_enum=False, length=32,
                ),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column('provider_id', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_column('provider_id')
        batch_op.drop_column('provider')

    with op.batch_alter_table('artist_albums', schema=None) as batch_op:
        batch_op.drop_index('ix_artist_albums_album_id')

    op.drop_table('artist_albums')
    # ### end Alembic commands ###
