name: Bug Report 

title: Change this title, poorly formatted issues will not be handled

description: Report bugs so we can fix them

labels: bug

body:

- type: dropdown
  attributes:
    label: System Operating System (OS)
    description: OS not listed here? Please let us know below
    options:
      - Windows
      - MacOS
      - Linux
      - Docker
      - Termux (Android)
  validations:
    required: true

- type: dropdown
  attributes:
    label: Python Version
    description: |
      You can find your Python version by running `python -V` on your CLI
      If you use a different Python version, please let us know below
    options:
      - 3.7 (CPython)
      - 3.8 (CPython)
      - 3.9 (CPython)
      - 3.10 (CPython)
  validations:
    required: true

- type: dropdown
  attributes:
    label: Install Source
    description: If installed from a different source, please let us know below
    options:
      - pip / PyPi
      - GitHub
      - Termux Installation Script (spotDL provided)
      - Arch User Repository (Unofficial)
  validations:
    required: true

- type: input
  attributes:
    label: Install version / commit hash
    description: |
      Supply version if installed from pip, found via `pip show spotdl`
      or supply commit hash if installed from GitHub
    placeholder: v3.x.x or hash-value
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected Behavior vs Actual Behavior
    placeholder: What did you expect and what actually happened? (Optional)

- type: textarea
  attributes:
    label: Steps to reproduce
    description: |
      Please ensure to include Spotify links and the actual command 
      you used.
    placeholder: |
      1.
      2.
      3.
      ...
  validations:
    required: true

- type: textarea
  attributes:
    label: Traceback
    description: Copy and paste the complete error message outputted by spotDL
    render: text
  validations:
    required: true
    

- type: textarea
  attributes:
    label: Other details
    placeholder: |
      Note anything else you can provide regarding the issue you're running into.

      If you didn't include your Python version, OS or installation source in the dropdowns
      earlier, note said details here. 
