"""SpotDL Core - Shared providers, matching, and types for SpotDL."""

from spotdl_core.matching import (
    FORBIDDEN_WORDS,
    MIN_ARTIST_MATCH,
    MIN_NAME_MATCH,
    MIN_TIME_MATCH,
    get_best_matches,
    get_best_result,
    order_results,
)
from spotdl_core.providers import (
    AppleMusicProvider,
    BandcampProvider,
    BandcampTargetProvider,
    DeezerProvider,
    DiscogsProvider,
    InvalidURLError,
    MetadataProvider,
    MetadataProviderError,
    MetadataResult,
    MusicBrainzProvider,
    NoResultsError,
    PipedProvider,
    SearchError,
    SoundCloudProvider,
    SoundCloudTargetProvider,
    SourceProvider,
    SourceProviderError,
    SpotifyProvider,
    TargetProvider,
    TargetProviderError,
    TidalProvider,
    TrackNotFoundError,
    URLResolver,
    URLResolverError,
    UnsupportedPlatformError,
    YouTubeMusicProvider,
    YouTubeMusicTargetProvider,
    YouTubeProvider,
    detect_platform,
    extract_url_info,
    get_resolver,
    is_valid_url,
)
from spotdl_core.download import (
    Archive,
    DownloadError,
    DownloadSettings,
    Downloader,
    generate_lrc,
    is_synced,
)
from spotdl_core.types import (
    Platform,
    Result,
    Song,
    SongError,
    SongList,
    TargetPlatform,
)

__all__ = [
    # Download
    "Archive",
    "DownloadError",
    "DownloadSettings",
    "Downloader",
    "generate_lrc",
    "is_synced",
    # Types
    "Platform",
    "Result",
    "Song",
    "SongError",
    "SongList",
    "TargetPlatform",
    # Matching
    "FORBIDDEN_WORDS",
    "MIN_ARTIST_MATCH",
    "MIN_NAME_MATCH",
    "MIN_TIME_MATCH",
    "get_best_matches",
    "get_best_result",
    "order_results",
    # Source Providers
    "AppleMusicProvider",
    "BandcampProvider",
    "DeezerProvider",
    "InvalidURLError",
    "SoundCloudProvider",
    "SourceProvider",
    "SourceProviderError",
    "SpotifyProvider",
    "TidalProvider",
    "TrackNotFoundError",
    "URLResolver",
    "URLResolverError",
    "UnsupportedPlatformError",
    "YouTubeMusicProvider",
    "detect_platform",
    "extract_url_info",
    "get_resolver",
    "is_valid_url",
    # Target Providers
    "BandcampTargetProvider",
    "NoResultsError",
    "PipedProvider",
    "SearchError",
    "SoundCloudTargetProvider",
    "TargetProvider",
    "TargetProviderError",
    "YouTubeMusicTargetProvider",
    "YouTubeProvider",
    # Metadata Providers
    "DiscogsProvider",
    "MetadataProvider",
    "MetadataProviderError",
    "MetadataResult",
    "MusicBrainzProvider",
]
