# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field, RootModel


class WsBatchFinished(BaseModel):
    batch_id: UUID = Field(..., title="Batch Id")
    cancelled: int = Field(..., title="Cancelled")
    completed: int = Field(..., title="Completed")
    failed: int = Field(..., title="Failed")
    m3u_paths: list[str] = Field(..., title="M3U Paths")
    save_file_path: str | None = Field(..., title="Save File Path")
    skipped: int = Field(..., title="Skipped")
    type: Literal["batch_finished"] = Field("batch_finished", title="Type")


class WsHello(BaseModel):
    protocol_version: int | None = Field(1, title="Protocol Version")
    type: Literal["hello"] = Field("hello", title="Type")


class WsJobCancelled(BaseModel):
    batch_id: UUID | None = Field(..., title="Batch Id")
    job_id: UUID = Field(..., title="Job Id")
    type: Literal["job_cancelled"] = Field("job_cancelled", title="Type")


class WsJobFailed(BaseModel):
    batch_id: UUID | None = Field(..., title="Batch Id")
    error: str | None = Field(..., title="Error")
    job_id: UUID = Field(..., title="Job Id")
    step: str | None = Field(..., title="Step")
    type: Literal["job_failed"] = Field("job_failed", title="Type")


class WsJobFinished(BaseModel):
    batch_id: UUID | None = Field(..., title="Batch Id")
    job_id: UUID = Field(..., title="Job Id")
    output_path: str | None = Field(..., title="Output Path")
    skip_reason: str | None = Field(..., title="Skip Reason")
    skipped: bool = Field(..., title="Skipped")
    status: Literal["completed"] = Field(..., title="Status")
    type: Literal["job_finished"] = Field("job_finished", title="Type")


class WsJobQueued(BaseModel):
    batch_id: UUID | None = Field(..., title="Batch Id")
    job_id: UUID = Field(..., title="Job Id")
    list_length: int | None = Field(..., title="List Length")
    list_position: int | None = Field(..., title="List Position")
    track_name: str | None = Field(..., title="Track Name")
    type: Literal["job_queued"] = Field("job_queued", title="Type")


class WsJobStarted(BaseModel):
    batch_id: UUID | None = Field(..., title="Batch Id")
    job_id: UUID = Field(..., title="Job Id")
    type: Literal["job_started"] = Field("job_started", title="Type")


class WsProgress(BaseModel):
    batch_id: UUID | None = Field(..., title="Batch Id")
    job_id: UUID = Field(..., title="Job Id")
    overall: float = Field(..., title="Overall")
    percent: int | None = Field(..., title="Percent")
    phase: str = Field(..., title="Phase")
    type: Literal["progress"] = Field("progress", title="Type")


class WsMessage(
    RootModel[
        WsHello
        | WsJobQueued
        | WsJobStarted
        | WsProgress
        | WsJobFinished
        | WsJobFailed
        | WsJobCancelled
        | WsBatchFinished
    ]
):
    root: (
        WsHello
        | WsJobQueued
        | WsJobStarted
        | WsProgress
        | WsJobFinished
        | WsJobFailed
        | WsJobCancelled
        | WsBatchFinished
    ) = Field(..., discriminator="type")
