/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as MatchingRouteImport } from './routes/matching'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as SongPlatformIdRouteImport } from './routes/song/$platform.$id'
import { Route as PlaylistPlatformIdRouteImport } from './routes/playlist/$platform.$id'
import { Route as ArtistPlatformIdRouteImport } from './routes/artist/$platform.$id'
import { Route as AlbumPlatformIdRouteImport } from './routes/album/$platform.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchingRoute = MatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SongPlatformIdRoute = SongPlatformIdRouteImport.update({
  id: '/song/$platform/$id',
  path: '/song/$platform/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistPlatformIdRoute = PlaylistPlatformIdRouteImport.update({
  id: '/playlist/$platform/$id',
  path: '/playlist/$platform/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistPlatformIdRoute = ArtistPlatformIdRouteImport.update({
  id: '/artist/$platform/$id',
  path: '/artist/$platform/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumPlatformIdRoute = AlbumPlatformIdRouteImport.update({
  id: '/album/$platform/$id',
  path: '/album/$platform/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/matching': typeof MatchingRoute
  '/queue': typeof QueueRoute
  '/settings': typeof SettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/album/$platform/$id': typeof AlbumPlatformIdRoute
  '/artist/$platform/$id': typeof ArtistPlatformIdRoute
  '/playlist/$platform/$id': typeof PlaylistPlatformIdRoute
  '/song/$platform/$id': typeof SongPlatformIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/matching': typeof MatchingRoute
  '/queue': typeof QueueRoute
  '/settings': typeof SettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/album/$platform/$id': typeof AlbumPlatformIdRoute
  '/artist/$platform/$id': typeof ArtistPlatformIdRoute
  '/playlist/$platform/$id': typeof PlaylistPlatformIdRoute
  '/song/$platform/$id': typeof SongPlatformIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/matching': typeof MatchingRoute
  '/queue': typeof QueueRoute
  '/settings': typeof SettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/album/$platform/$id': typeof AlbumPlatformIdRoute
  '/artist/$platform/$id': typeof ArtistPlatformIdRoute
  '/playlist/$platform/$id': typeof PlaylistPlatformIdRoute
  '/song/$platform/$id': typeof SongPlatformIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/matching'
    | '/queue'
    | '/settings'
    | '/auth/login'
    | '/auth/register'
    | '/album/$platform/$id'
    | '/artist/$platform/$id'
    | '/playlist/$platform/$id'
    | '/song/$platform/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/matching'
    | '/queue'
    | '/settings'
    | '/auth/login'
    | '/auth/register'
    | '/album/$platform/$id'
    | '/artist/$platform/$id'
    | '/playlist/$platform/$id'
    | '/song/$platform/$id'
  id:
    | '__root__'
    | '/'
    | '/matching'
    | '/queue'
    | '/settings'
    | '/auth/login'
    | '/auth/register'
    | '/album/$platform/$id'
    | '/artist/$platform/$id'
    | '/playlist/$platform/$id'
    | '/song/$platform/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatchingRoute: typeof MatchingRoute
  QueueRoute: typeof QueueRoute
  SettingsRoute: typeof SettingsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AlbumPlatformIdRoute: typeof AlbumPlatformIdRoute
  ArtistPlatformIdRoute: typeof ArtistPlatformIdRoute
  PlaylistPlatformIdRoute: typeof PlaylistPlatformIdRoute
  SongPlatformIdRoute: typeof SongPlatformIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matching': {
      id: '/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof MatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/song/$platform/$id': {
      id: '/song/$platform/$id'
      path: '/song/$platform/$id'
      fullPath: '/song/$platform/$id'
      preLoaderRoute: typeof SongPlatformIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$platform/$id': {
      id: '/playlist/$platform/$id'
      path: '/playlist/$platform/$id'
      fullPath: '/playlist/$platform/$id'
      preLoaderRoute: typeof PlaylistPlatformIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$platform/$id': {
      id: '/artist/$platform/$id'
      path: '/artist/$platform/$id'
      fullPath: '/artist/$platform/$id'
      preLoaderRoute: typeof ArtistPlatformIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$platform/$id': {
      id: '/album/$platform/$id'
      path: '/album/$platform/$id'
      fullPath: '/album/$platform/$id'
      preLoaderRoute: typeof AlbumPlatformIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatchingRoute: MatchingRoute,
  QueueRoute: QueueRoute,
  SettingsRoute: SettingsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AlbumPlatformIdRoute: AlbumPlatformIdRoute,
  ArtistPlatformIdRoute: ArtistPlatformIdRoute,
  PlaylistPlatformIdRoute: PlaylistPlatformIdRoute,
  SongPlatformIdRoute: SongPlatformIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
