"""Structural seams the view-models depend on (CONTRACT A).

``SpotdlClientProtocol`` is the sole surface through which a view-model reaches the
server; the real :class:`~spotdl_cli.client.SpotdlClient` satisfies it structurally
and the tests' ``FakeSpotdlClient`` implements it from canned data. ``CredentialStore``
and ``ConfigStore`` are the companion local-storage seams (Plan 8's ``config.py``
provides concrete adapters in ``commands/tui.py``; tests inject fakes).

Defining these as ``Protocol``\\s keeps the view-models framework-free: they never
import the concrete client, transport, or generated models — only the ``views.*``
presentation types that cross the boundary.
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from contextlib import AbstractAsyncContextManager
from typing import Literal, Protocol
from uuid import UUID

from spotdl_cli.config import CliConfig
from spotdl_cli.views import (
    AlbumView,
    ArtistView,
    BatchView,
    ConfigView,
    DownloadPage,
    DownloadSubmit,
    EntityView,
    JobView,
    LyricsView,
    MatchView,
    PagedUsersView,
    PatCreated,
    PlaylistView,
    ReportView,
    SearchResultView,
    StatsView,
    Tokens,
    TrackView,
    UserView,
    WsMessage,
)

VoteValue = Literal["up", "down", "retract"]


class SpotdlClientProtocol(Protocol):
    """The façade surface the view-models call (a subset of ``SpotdlClient``)."""

    async def config(self) -> ConfigView: ...
    async def download_config(self) -> ConfigView: ...
    async def resolve(self, query: str) -> EntityView: ...
    async def search(self, q: str, *, limit: int = 10) -> SearchResultView: ...
    async def track(self, id: UUID) -> TrackView: ...
    async def album(self, id: UUID) -> AlbumView: ...
    async def artist(self, id: UUID) -> ArtistView: ...
    async def playlist(self, id: UUID) -> PlaylistView: ...
    async def matches(self, track_id: UUID) -> list[MatchView]: ...
    async def submit_match(self, track_id: UUID, url: str) -> MatchView: ...
    async def vote_match(self, id: UUID, value: VoteValue) -> MatchView: ...
    async def lyrics(self, track_id: UUID) -> list[LyricsView]: ...
    async def vote_lyrics(self, id: UUID, value: VoteValue) -> LyricsView: ...
    async def me(self, *, token: str) -> UserView: ...
    async def login_password(self, email: str, password: str) -> Tokens: ...
    async def register(self, email: str, password: str) -> Tokens: ...
    async def create_pat(self, name: str, *, access_token: str) -> PatCreated: ...
    async def submit_download(self, req: DownloadSubmit) -> BatchView: ...
    async def list_downloads(
        self,
        *,
        status: str | None = None,
        batch_id: UUID | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> DownloadPage: ...
    async def get_download(self, job_id: UUID) -> JobView: ...
    async def cancel_download(self, job_id: UUID) -> JobView: ...
    async def get_batch(self, batch_id: UUID) -> BatchView: ...
    async def submit_report(
        self,
        subject_type: str,
        subject_id: UUID,
        *,
        field: str | None = None,
        proposed_value: str | None = None,
        reason: str | None = None,
    ) -> ReportView: ...
    async def my_reports(self) -> list[ReportView]: ...
    async def admin_reports(self, *, status: str = "pending") -> list[ReportView]: ...
    async def approve_report(self, id: UUID, *, note: str | None = None) -> ReportView: ...
    async def reject_report(self, id: UUID, *, note: str | None = None) -> ReportView: ...
    async def admin_stats(self) -> StatsView: ...
    async def admin_users(self, *, limit: int = 50, offset: int = 0) -> PagedUsersView: ...

    async def revoke_pat(self, token_id: UUID, *, access_token: str) -> None:
        """Best-effort server-side PAT revocation (``DELETE /auth/tokens/{id}``)."""
        ...

    def progress(self) -> AbstractAsyncContextManager[AsyncIterator[WsMessage]]:
        """Open the ``/ws/progress`` stream (an async context manager over frames)."""
        ...


class CredentialStore(Protocol):
    """The PAT store keyed by server origin (Plan 8 ``config.py`` credentials)."""

    def get_token(self, origin: str) -> str | None: ...
    def get_token_id(self, origin: str) -> str | None: ...
    def store_token(self, origin: str, token: str, email: str) -> None: ...
    def delete_token(self, origin: str) -> None: ...


class ConfigStore(Protocol):
    """The ``CliConfig`` load/save seam the settings view-model edits."""

    def load(self) -> CliConfig: ...
    def save(self, cfg: CliConfig) -> None: ...
