name: Standard code checks (MyPy/Pylint/Black/Isort)

on: [push, pull_request]

jobs:
  checks:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true

      - name: Install dependencies
        run: |
          uv venv --python 3.11
          uv sync
          uv pip install pip

      - name: Run Pylint check
        run: |
          uv run pylint --fail-under 10 --limit-inference-results 0 --disable=R0917 ./spotdl

      - name: Run MyPy check
        run: |
          uv run mypy --ignore-missing-imports --follow-imports silent --install-types --non-interactive ./spotdl

      - name: Run Black check
        run: |
          uv run black --check ./spotdl

      - name: Run isort check
        run: |
          uv run isort --check --diff ./spotdl
